import type { Recipe, Ingredient, User } from './types'

export const mockUser: User = {
  id: '1',
  email: 'user@example.com',
  name: '김요리',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
  createdAt: new Date('2024-01-01'),
}

export const mockIngredients: Ingredient[] = [
  { id: '1', name: '계란', category: 'dairy' },
  { id: '2', name: '대파', category: 'vegetable' },
  { id: '3', name: '밥', category: 'grain' },
  { id: '4', name: '김치', category: 'vegetable' },
  { id: '5', name: '돼지고기', category: 'meat' },
  { id: '6', name: '양파', category: 'vegetable' },
  { id: '7', name: '마늘', category: 'seasoning' },
  { id: '8', name: '간장', category: 'seasoning' },
  { id: '9', name: '참기름', category: 'seasoning' },
  { id: '10', name: '두부', category: 'other' },
  { id: '11', name: '라면', category: 'grain' },
  { id: '12', name: '치즈', category: 'dairy' },
  { id: '13', name: '소시지', category: 'meat' },
  { id: '14', name: '감자', category: 'vegetable' },
  { id: '15', name: '당근', category: 'vegetable' },
  { id: '16', name: '고추장', category: 'seasoning' },
  { id: '17', name: '된장', category: 'seasoning' },
  { id: '18', name: '버터', category: 'dairy' },
  { id: '19', name: '닭고기', category: 'meat' },
  { id: '20', name: '새우', category: 'seafood' },
]

export const mockRecipes: Recipe[] = [
  {
    id: '1',
    title: '김치볶음밥',
    description: '자취생의 영원한 친구! 신김치와 밥만 있으면 뚝딱 만드는 간단 한끼',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&h=400&fit=crop',
    cookTime: 15,
    difficulty: 'easy',
    servings: 1,
    ingredients: [
      { ingredient: mockIngredients[2], amount: '1공기' },
      { ingredient: mockIngredients[3], amount: '1/2컵' },
      { ingredient: mockIngredients[0], amount: '1개' },
      { ingredient: mockIngredients[8], amount: '1큰술' },
    ],
    steps: [
      { order: 1, description: '김치를 잘게 썰어주세요', duration: 2 },
      { order: 2, description: '팬에 기름을 두르고 김치를 볶아주세요', duration: 3 },
      { order: 3, description: '밥을 넣고 함께 볶아주세요', duration: 5 },
      { order: 4, description: '참기름을 넣고 계란 프라이를 올려 완성!', duration: 5 },
    ],
    nutrition: { calories: 450, protein: 12, carbs: 65, fat: 15 },
    author: mockUser,
    likes: 1234,
    saves: 567,
    createdAt: new Date('2024-03-15'),
    tags: ['자취요리', '간단', '한식', '볶음밥'],
  },
  {
    id: '2',
    title: '계란볶음밥',
    description: '달걀과 밥의 완벽한 조합, 5분이면 완성되는 초간단 레시피',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&h=400&fit=crop',
    cookTime: 10,
    difficulty: 'easy',
    servings: 1,
    ingredients: [
      { ingredient: mockIngredients[2], amount: '1공기' },
      { ingredient: mockIngredients[0], amount: '2개' },
      { ingredient: mockIngredients[1], amount: '1대' },
      { ingredient: mockIngredients[7], amount: '1큰술' },
    ],
    steps: [
      { order: 1, description: '대파를 송송 썰어주세요', duration: 1 },
      { order: 2, description: '팬에 기름을 두르고 계란을 스크램블해주세요', duration: 2 },
      { order: 3, description: '밥을 넣고 볶다가 간장으로 간을 맞춰주세요', duration: 5 },
      { order: 4, description: '대파를 넣고 마무리!', duration: 2 },
    ],
    nutrition: { calories: 380, protein: 15, carbs: 55, fat: 12 },
    author: mockUser,
    likes: 892,
    saves: 345,
    createdAt: new Date('2024-03-14'),
    tags: ['자취요리', '초간단', '볶음밥'],
  },
  {
    id: '3',
    title: '된장찌개',
    description: '구수한 된장 향이 가득한 따끈한 국물 요리, 자취방도 집밥 느낌!',
    image: 'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=600&h=400&fit=crop',
    cookTime: 25,
    difficulty: 'medium',
    servings: 2,
    ingredients: [
      { ingredient: mockIngredients[16], amount: '2큰술' },
      { ingredient: mockIngredients[9], amount: '1/2모' },
      { ingredient: mockIngredients[5], amount: '1/2개' },
      { ingredient: mockIngredients[6], amount: '2쪽' },
      { ingredient: mockIngredients[1], amount: '1대' },
    ],
    steps: [
      { order: 1, description: '두부와 양파를 먹기 좋은 크기로 썰어주세요', duration: 3 },
      { order: 2, description: '냄비에 물을 붓고 된장을 풀어주세요', duration: 2 },
      { order: 3, description: '양파와 마늘을 넣고 끓여주세요', duration: 10 },
      { order: 4, description: '두부를 넣고 5분 더 끓여주세요', duration: 5 },
      { order: 5, description: '대파를 넣고 마무리!', duration: 5 },
    ],
    nutrition: { calories: 180, protein: 12, carbs: 15, fat: 8 },
    author: mockUser,
    likes: 2156,
    saves: 987,
    createdAt: new Date('2024-03-13'),
    tags: ['국물요리', '한식', '된장', '집밥'],
  },
  {
    id: '4',
    title: '라면',
    description: '모든 자취생의 영혼의 음식, 취향껏 토핑을 추가해보세요',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&h=400&fit=crop',
    cookTime: 8,
    difficulty: 'easy',
    servings: 1,
    ingredients: [
      { ingredient: mockIngredients[10], amount: '1봉' },
      { ingredient: mockIngredients[0], amount: '1개' },
      { ingredient: mockIngredients[1], amount: '조금' },
    ],
    steps: [
      { order: 1, description: '물 550ml를 끓여주세요', duration: 3 },
      { order: 2, description: '스프와 면을 넣어주세요', duration: 4 },
      { order: 3, description: '계란과 대파를 넣고 마무리!', duration: 1 },
    ],
    nutrition: { calories: 550, protein: 10, carbs: 75, fat: 20 },
    author: mockUser,
    likes: 3421,
    saves: 1234,
    createdAt: new Date('2024-03-12'),
    tags: ['라면', '야식', '초간단'],
  },
  {
    id: '5',
    title: '치즈 감자전',
    description: '바삭한 감자전에 치즈를 듬뿍! 맥주 안주로도 최고',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&h=400&fit=crop',
    cookTime: 20,
    difficulty: 'medium',
    servings: 2,
    ingredients: [
      { ingredient: mockIngredients[13], amount: '2개' },
      { ingredient: mockIngredients[11], amount: '1장' },
      { ingredient: mockIngredients[5], amount: '1/4개' },
    ],
    steps: [
      { order: 1, description: '감자를 강판에 곱게 갈아주세요', duration: 5 },
      { order: 2, description: '양파를 잘게 다져 섞어주세요', duration: 2 },
      { order: 3, description: '팬에 기름을 두르고 노릇하게 부쳐주세요', duration: 10 },
      { order: 4, description: '치즈를 올리고 뚜껑을 덮어 녹여주세요', duration: 3 },
    ],
    nutrition: { calories: 320, protein: 8, carbs: 35, fat: 16 },
    author: mockUser,
    likes: 1567,
    saves: 678,
    createdAt: new Date('2024-03-11'),
    tags: ['안주', '감자', '치즈', '전'],
  },
  {
    id: '6',
    title: '소시지 야채볶음',
    description: '알록달록 야채와 소시지의 만남, 도시락 반찬으로도 굿!',
    image: 'https://images.unsplash.com/photo-1432139509613-5c4255815697?w=600&h=400&fit=crop',
    cookTime: 15,
    difficulty: 'easy',
    servings: 2,
    ingredients: [
      { ingredient: mockIngredients[12], amount: '4개' },
      { ingredient: mockIngredients[5], amount: '1/2개' },
      { ingredient: mockIngredients[14], amount: '1/2개' },
      { ingredient: mockIngredients[15], amount: '1큰술' },
    ],
    steps: [
      { order: 1, description: '소시지와 야채를 먹기 좋게 썰어주세요', duration: 3 },
      { order: 2, description: '팬에 기름을 두르고 소시지를 볶아주세요', duration: 4 },
      { order: 3, description: '야채를 넣고 함께 볶아주세요', duration: 5 },
      { order: 4, description: '고추장으로 간을 맞춰주세요', duration: 3 },
    ],
    nutrition: { calories: 280, protein: 10, carbs: 20, fat: 18 },
    author: mockUser,
    likes: 987,
    saves: 456,
    createdAt: new Date('2024-03-10'),
    tags: ['반찬', '도시락', '볶음'],
  },
]

export const popularTags = [
  '자취요리',
  '초간단',
  '한식',
  '야식',
  '다이어트',
  '술안주',
  '도시락',
  '국물요리',
  '볶음밥',
  '파스타',
]
